
import java.util.ArrayList;
import java.util.Collections;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author noahgillis
 */
public class MeanMedianMode extends javax.swing.JFrame {

    /**
     * Creates new form MeanMedianMode
     */
    public MeanMedianMode() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        setData = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        calculateMean = new javax.swing.JButton();
        calculateMedian = new javax.swing.JButton();
        calculateMode = new javax.swing.JButton();
        calcAll = new javax.swing.JButton();
        close = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        meanLabel = new javax.swing.JLabel();
        medianLabel = new javax.swing.JLabel();
        modeLabel = new javax.swing.JLabel();
        realMeanLabel = new javax.swing.JLabel();
        realMedianLabel = new javax.swing.JLabel();
        realModeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter your data separated by a comma, then select function to perform");

        jLabel2.setText("Ex: 12, 4,7, 32,3");

        jLabel3.setText("Data:");

        calculateMean.setText("Calculate Mean");
        calculateMean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateMeanActionPerformed(evt);
            }
        });

        calculateMedian.setText("Calculate Median");
        calculateMedian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateMedianActionPerformed(evt);
            }
        });

        calculateMode.setText("Calculate Mode");
        calculateMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateModeActionPerformed(evt);
            }
        });

        calcAll.setText("Calculate Mean, Median, and Mode");
        calcAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcAllActionPerformed(evt);
            }
        });

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        realMedianLabel.setText(" ");

        realModeLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(setData, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calculateMean)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calculateMedian)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calculateMode))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(modeLabel)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(meanLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(medianLabel)
                                .addGap(40, 40, 40))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(calcAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(close)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(realModeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(realMeanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(realMedianLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(setData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(calculateMean)
                        .addComponent(calculateMedian)
                        .addComponent(calculateMode)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcAll)
                    .addComponent(close))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(meanLabel)
                        .addGap(18, 18, 18)
                        .addComponent(medianLabel))
                    .addComponent(realMeanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(realMedianLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(realModeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modeLabel)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        realMedianLabel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeActionPerformed

    private void calcAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcAllActionPerformed
        calculate("all");
    }//GEN-LAST:event_calcAllActionPerformed

    private void calculateMeanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateMeanActionPerformed
        calculate("mean");
    }//GEN-LAST:event_calculateMeanActionPerformed

    private void calculateMedianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateMedianActionPerformed
        calculate("median");
    }//GEN-LAST:event_calculateMedianActionPerformed

    private void calculateModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateModeActionPerformed
        calculate("mode");
    }//GEN-LAST:event_calculateModeActionPerformed

    public void calculate (String calcToPerform) {
        ArrayList<Integer> numbers = new ArrayList<>();
        numbers = getListOfNumbers();
        
        // Collections is in zyBook, section 11.1
        Collections.sort(numbers);
        
        double mode = 0;
        switch (calcToPerform) {
            case "mean":
                calculateMean(numbers, true);
                break;
            case "median":
                calculateMedian(numbers, true);
                break;
            case "mode":
                calculateMode(numbers, true);
                break;
            case "all":
                calculateMean(numbers, false);
                calculateMedian(numbers, false);
                calculateMode(numbers, false);
                break;
        }
    }
    
    public void calculateMean(ArrayList<Integer> numbers, boolean censor) {
        double mean = 0;
        
        for (int number : numbers) {
            mean += number;
        }
        
        mean = mean / numbers.size();
        realMeanLabel.setText("Mean: " + mean);
        
        if (censor) {
            realMedianLabel.setText("");
            realModeLabel.setText("");
        }
    }
    
    public void calculateMedian(ArrayList<Integer> numbers, boolean censor) {
        double median = 0;
        
        if (numbers.size() % 2 == 0) {
            median = numbers.get(numbers.size() / 2 - 1)
                + (numbers.get(numbers.size() / 2));
            median = median / 2;
        } else {
            median = numbers.get(numbers.size() / 2);
        }
        
        if (censor) {    
            realMeanLabel.setText("");
            realModeLabel.setText("");
        }
        
        realMedianLabel.setText("Median: " + median);

    }
    
    public void calculateMode(ArrayList<Integer> numbers, boolean censor) {
        int highestNumber = 0;
        int mode = 0;
        
        for (int i = 0; i < numbers.size(); ++i) {
            int count = 0;
            
            for (int a = 0; a < numbers.size(); ++a) {
                if (numbers.get(i).equals(numbers.get(a))) {
                   ++count; 
                } 
            }

            if (count > highestNumber) {
                highestNumber = count;
                mode = numbers.get(i);
            }
        }
        
        if (censor) {
            realMeanLabel.setText("");
            realMedianLabel.setText("");
        }
        
        realModeLabel.setText("Mode: " + mode);
    }
    
    public ArrayList<Integer> getListOfNumbers () {
        ArrayList<Integer> numbers = new ArrayList<>();
        String text = setData.getText();
        
        // I like to think of this part as the 'chopping block'.
        do {
            // Find comma
            int commaIndex = text.indexOf(',');
            
            // Test comma index
            System.out.println("commaIndex: " + commaIndex);

            String numberStr;
            
            // If there is a comma
            if (commaIndex != -1) {
                // Chop at comma, trim inedible parts
                numberStr = text.substring(0, commaIndex).trim();
            
                // Test that the computer did not chop any fingers
                System.out.println("number: " + numberStr);
                
                // Give a reminder to the computer that it just chopped
                text = text.substring(commaIndex + 1);
            } else { // If there is no comma
                // Chop off the inedible parts, not the food
                numberStr = text.trim();
                
                // Test to ensure that no fingers were chopped
                System.out.println("number: " + numberStr);
                
                // Tell the computer it is done chopping
                text = "";
            }

            // If there is any food from chopping, add the food to the pot
            if (!numberStr.isEmpty()) {
                numbers.add(Integer.parseInt(numberStr));
            }
            
        } while (!text.isEmpty());
        
        return numbers;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeanMedianMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeanMedianMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeanMedianMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeanMedianMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeanMedianMode().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcAll;
    private javax.swing.JButton calculateMean;
    private javax.swing.JButton calculateMedian;
    private javax.swing.JButton calculateMode;
    private javax.swing.JButton close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel meanLabel;
    private javax.swing.JLabel medianLabel;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JLabel realMeanLabel;
    private javax.swing.JLabel realMedianLabel;
    private javax.swing.JLabel realModeLabel;
    private javax.swing.JTextField setData;
    // End of variables declaration//GEN-END:variables
}
